"""empty message

Revision ID: 550bb13263e8
Revises: b9188103b5dd
Create Date: 2024-09-13 12:00:23.865030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550bb13263e8'
down_revision = 'b9188103b5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
